name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: TVOS Version
      options:
        - tvOS 18
        - tvOS 17
        - tvOS 16
        - Other
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device Model
      options:
        - Apple TV 4K (3rd gen)
        - Apple TV 4K (2nd gen)
        - Apple TV 4K (1st gen)
        - Apple TV HD
    validations:
      required: true
